# Generated by Django 5.0 on 2023-12-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='author',
            field=models.CharField(default='Harsh', max_length=100),
        ),
        migrations.AddField(
            model_name='library',
            name='genre',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
